env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: {linebreak-style: ['error', 'windows'], no-console: off, object-curly-spacing: off, object-curly-newline: off}
ignorePatterns: ['/dist/**']
